"""Markdown Run Ledger — structured lab notebook from case directory.

Produces a factual Markdown log suitable for research notes:
  - files, commands, parameters
  - output summaries (energy, EF, λ, Tc, phonon)
  - issues and decision
  - next actions
  - no LLM, no fabrication — only deterministic results
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from vibedft.core.review import review_case
from vibedft.analyzers.orchestrator import run_physics_analysis
from vibedft.decision.publication_gate import decide
from vibedft.convergence.parameter_extractor import extract_parameters
from vibedft.convergence.metrics import extract_metrics


def collect_log(case_dir: Path | str, output: Path | str | None = None) -> str:
    """Generate a Markdown Run Ledger for a case directory.

    Args:
        case_dir: Path to the VibeDFT case directory.
        output: Optional output file path.

    Returns:
        The complete Markdown string.
    """
    d = Path(case_dir).resolve()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # ── Gather all deterministic results ──
    review = review_case(d)
    physics = run_physics_analysis(d, review_result=review)
    decision = decide(d, review_result=review, physics_report=physics)

    # Parameter extraction (from input files)
    from vibedft.convergence.scanner import _scan_case_dir
    snap = _scan_case_dir(d)
    params = extract_parameters(snap)
    metrics = extract_metrics(snap)

    # ── Build Markdown ──
    md: list[str] = []
    _h(md, 1, f"Run Ledger: {d.name}")
    md.append(f"**Generated:** {now}  ")
    md.append(f"**Path:** `{d}`  ")
    md.append("")

    # ── Parameters ──
    _h(md, 2, "Input Parameters")
    md.append("| Parameter | Value |")
    md.append("|---|---|")
    for k in sorted(params):
        v = params[k]
        if v is not None and v != 0 and v != "":
            md.append(f"| `{k}` | `{v}` |")
    md.append("")

    # ── Output Summary ──
    _h(md, 2, "Output Summary")
    md.append("| Metric | Value |")
    md.append("|---|---|")
    key_metrics = [
        ("λ_max", metrics.get("lambda_max")),
        ("Tc_max (K)", metrics.get("tc_max_K")),
        ("ωlog (K)", metrics.get("omega_log_K")),
        ("DOS@EF", metrics.get("dos_at_ef")),
        ("EF (eV)", metrics.get("fermi_energy_ev")),
        ("Min phonon freq (cm⁻¹)", metrics.get("min_phonon_freq_cm1")),
        ("Imaginary modes", metrics.get("n_imaginary_modes")),
        ("Imaginary non-Γ", metrics.get("n_imaginary_non_gamma")),
        ("SCF converged", _check(metrics.get("scf_converged"))),
    ]
    for label, val in key_metrics:
        if val is not None:
            md.append(f"| {label} | {_fmt(val)} |")
    md.append("")

    # ── Physics Scores ──
    _h(md, 2, "Physics Scores")
    scores = physics.to_dict().get("scores", {}) if physics else {}
    md.append("| Score | Value |")
    md.append("|---|---|")
    for k, v in scores.items():
        md.append(f"| {k} | {v:.1f}/10 |")
    md.append(f"| Verdict | {physics.overall_verdict if physics else 'N/A'} |")
    md.append("")

    # ── Issues ──
    _h(md, 2, "Issues")
    errors = [i for i in review.all_issues if _sev(i) == "error"]
    warnings = [i for i in review.all_issues if _sev(i) == "warning"]
    if errors:
        md.append(f"**{len(errors)} errors**  ")
        for e in errors[:10]:
            md.append(f"- ❌ `{e.id}` — {e.message}")
    else:
        md.append("✅ No errors.  ")
    if warnings:
        md.append(f"**{len(warnings)} warnings**  ")
        for w in warnings[:10]:
            md.append(f"- ⚠️ `{w.id}` — {w.message}")
    md.append("")

    # ── Decision ──
    _h(md, 2, "Decision")
    gate_icon = {"BLOCKED": "🔴", "NEEDS_CONVERGENCE": "🟡", "PROMISING": "🟢", "READY_FOR_FIGURES": "✅"}
    icon = gate_icon.get(decision.gate.value, "?")
    md.append(f"**{icon} {decision.gate.value}**  ")
    md.append(f"{decision.summary}  ")
    if decision.primary_blocker:
        md.append(f"\n**Primary:** {decision.primary_blocker}  ")
    md.append("")

    # ── Next Actions ──
    _h(md, 2, "Next Actions")
    for i, a in enumerate(decision.next_actions, 1):
        md.append(f"{i}. {a}")
    md.append("")

    # ── Files ──
    _h(md, 2, "Files")
    for f in review.inspection.files:
        icon = "✅" if f.parse_status == "ok" else "❌"
        md.append(f"- {icon} `{Path(f.path).name}` — {f.program.value} — {f.summary}")

    md.append("")
    md.append("---")
    md.append(f"*Generated by VibeDFT v0.1.0*")

    result = "\n".join(md)
    if output:
        Path(output).write_text(result, encoding="utf-8")
    return result


def _h(md: list[str], level: int, text: str) -> None:
    md.append(f"{'#' * level} {text}")
    md.append("")


def _sev(iss) -> str:
    try:
        return iss.severity.value
    except AttributeError:
        return "?"


def _fmt(val) -> str:
    if val is None:
        return "N/A"
    if isinstance(val, float):
        return f"{val:.4f}"
    return str(val)


def _check(val) -> str:
    if val is True:
        return "✅ Yes"
    if val is False:
        return "❌ No"
    return str(val)
