"""Workflow executor: plan → directory tree with inputs, sbatch, READMEs, manifest."""

from __future__ import annotations

import json
from pathlib import Path
from datetime import datetime, timezone

from vibedft.generators.manifest import WorkflowPlan, StageSpec
from vibedft.generators.workflow_planner import plan_superconductivity
from vibedft.generators.qe_input_builder import build_stage_input
from vibedft.generators.slurm_builder import (
    build_slurm_script,
    build_submit_all,
    build_stage_readme,
)
from vibedft.generators.convergence_matrix import generate_convergence_readme


def execute_plan(plan: WorkflowPlan) -> Path:
    """Create the full directory tree from a workflow plan.

    Returns the output root path.
    """
    root = Path(plan.output_root)
    root.mkdir(parents=True, exist_ok=True)

    # ── Manifest ──
    manifest = plan.to_manifest()
    manifest["generated_at"] = datetime.now(timezone.utc).isoformat()
    manifest["generator_version"] = "vibedft/0.1.0"
    (root / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    # ── Root README ──
    (root / "README.md").write_text(_root_readme(plan), encoding="utf-8")

    # ── Per-stage directories ──
    for stage in plan.stages:
        stage_dir = root / stage.directory
        stage_dir.mkdir(parents=True, exist_ok=True)

        # Input file
        if stage.template:
            in_content = build_stage_input(stage, plan)
            (stage_dir / stage.input_file).write_text(in_content, encoding="utf-8")

        # Slurm script
        slurm_content = build_slurm_script(stage, plan)
        (stage_dir / "run.sbatch").write_text(slurm_content, encoding="utf-8")

        # Stage README
        (stage_dir / "README.md").write_text(build_stage_readme(stage, plan), encoding="utf-8")

    # ── submit_all.sh ──
    (root / "submit_all.sh").write_text(build_submit_all(plan, plan.stages), encoding="utf-8")

    return root


def _root_readme(plan: WorkflowPlan) -> str:
    lines = [
        f"# {plan.plan_id}",
        "",
        f"Generated by VibeDFT — {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Workflow Stages",
        "",
    ]
    for s in plan.stages:
        deps = f" (after {', '.join(s.depends_on)})" if s.depends_on else ""
        lines.append(f"- **{s.id}**: {s.kind.value} → `{s.directory}/`{deps}")

    lines.extend([
        "",
        "## Execution Policy",
        "",
        "- **ALL QE execution goes through Slurm sbatch.**",
        "- Direct binary execution on login nodes is FORBIDDEN.",
        "- Lightweight outputs only — heavy files (out/, *.save/, _ph0/, *.wfc*, elph_dir/) are excluded.",
        "",
        "## Submit All",
        "",
        "```bash",
        "bash submit_all.sh",
        "```",
        "",
        "## Review",
        "",
        "```bash",
        "vibedft review --case-dir .",
        "vibedft report generate --case-dir . --output report.html",
        "```",
        "",
        "## Convergence (after all jobs complete)",
        "",
        "```bash",
        "vibedft convergence --root . --html convergence.html",
        "```",
    ])
    return "\n".join(lines) + "\n"
