"""Slurm script builder — sbatch-only, no direct QE execution.

All QE execution MUST go through ``sbatch + srun``.  Direct execution
on login nodes (``mpirun pw.x < in > out``) is FORBIDDEN.

The launcher defaults to ``srun`` and is configurable via the profile.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from vibedft.generators.manifest import StageSpec, WorkflowPlan

# Launcher templates:
#   {launcher} — launcher command (srun | mpirun)
#   {np}       — number of MPI ranks
#   {exe}      — full path to the QE executable
#   {input}    — input file name
#   {output}   — output file name
_LAUNCHER_TEMPLATES = {
    "srun": "{launcher} -n {np} {exe} -in {input} > {output}",
    "mpirun": "{launcher} -np {np} {exe} < {input} > {output}",
}


def build_slurm_script(stage: StageSpec, plan: WorkflowPlan) -> str:
    """Build a Slurm sbatch script for a single workflow stage.

    All QE execution goes through srun inside the sbatch script.
    Direct execution on login nodes is NEVER emitted.
    """
    prof = plan.profile
    launcher_name = getattr(prof, "launcher", "srun") or "srun"

    launcher_template = _LAUNCHER_TEMPLATES.get(launcher_name)
    if launcher_template is None:
        raise ValueError(
            f"Unknown launcher '{launcher_name}'. "
            f"Supported: {', '.join(_LAUNCHER_TEMPLATES)}"
        )

    lines = [
        "#!/bin/bash",
        f"#SBATCH --mem=0",
        f"#SBATCH -J {_safe_job_name(stage)}",
        f"#SBATCH -p {prof.partition}",
        f"#SBATCH --time={stage.walltime}",
        f"#SBATCH -N 1",
        f"#SBATCH -n {stage.cores}",
        f"#SBATCH -o {stage.id}-%j.out",
        f"#SBATCH -e {stage.id}-%j.err",
        "",
        "set -u",
        "",
        "# Intel environment",
        'if [ -z "${SETVARS_COMPLETED:-}" ]; then',
        "  set +u",
        f"  source {prof.intel_setvars} 2>/dev/null",
        "  set -u",
        "fi",
        "",
        f"export OMP_NUM_THREADS=1",
        f'QE_BIN="{prof.qe_bin_dir}"',
        "",
        f'cd "{plan.output_root}/{stage.directory}" || exit 1',
        "",
    ]

    # Pre-commands (SCF save staging, etc.)
    for cmd in stage.pre_commands:
        if cmd.strip() and not cmd.strip().startswith("#"):
            lines.append(cmd)
        elif cmd.strip().startswith("#"):
            lines.append(cmd)

    if stage.pre_commands:
        lines.append("")

    # Main execution
    if stage.executable and stage.input_file and stage.output_file:
        lines.append(f'echo "=== {stage.id}: {stage.executable} ==="')
        exe_path = f'"$QE_BIN/{stage.executable}"'
        if launcher_name == "mpirun":
            exec_line = (
                f'{launcher_template.format(launcher=launcher_name, np=stage.cores, exe=exe_path, input=stage.input_file, output=stage.output_file)}'
            )
        else:
            exec_line = (
                f'{launcher_template.format(launcher=launcher_name, np=stage.cores, exe=f"$QE_BIN/{stage.executable}", input=stage.input_file, output=stage.output_file)}'
            )
        lines.append(exec_line)
        lines.append("ret=$?")
        lines.append('if [ "$ret" -ne 0 ]; then')
        lines.append(f'  echo "{stage.id} FAILED with exit code $ret"')
        lines.append("  exit $ret")
        lines.append("fi")
        lines.append(f'echo "{stage.id} completed"')

    # Manual/post-processing stage
    if not stage.executable:
        for cmd in stage.pre_commands:
            if cmd.strip() and not cmd.strip().startswith("#"):
                lines.append(cmd)

    lines.append("")
    lines.append('echo "=== Job Complete ==="')
    return "\n".join(lines) + "\n"


def build_submit_all(plan: WorkflowPlan, stages: list[StageSpec]) -> str:
    """Build a submit_all.sh script that submits all stages via sbatch.

    Stages without dependencies are submitted immediately; dependent stages
    use --dependency=afterok.  All execution goes through sbatch.
    """
    lines = [
        "#!/bin/bash",
        "# submit_all.sh — generated by VibeDFT",
        "# ALL execution goes through Slurm sbatch. Direct QE execution is FORBIDDEN.",
        "#",
        f"# Plan: {plan.plan_id}",
        f"# Engine: {plan.engine}",
        f"# Profile: {plan.profile.name}",
        "",
        "set -u",
        "",
        f'ROOT="{plan.output_root}"',
        "",
    ]

    # Track job IDs for dependency chaining
    stage_job_var: dict[str, str] = {}

    for s in stages:
        var_name = f"JOB_{s.id.replace('-', '_')}"
        slurm_path = f"{s.directory}/run.sbatch"
        deps = s.depends_on

        if not deps:
            lines.append(f"# Submit: {s.id}")
            lines.append(f'{var_name}=$(cd "$ROOT/{s.directory}" && sbatch run.sbatch | '
                        f"awk '{{print $NF}}')")
        else:
            dep_vars = ":".join(f"${stage_job_var[d]}" for d in deps if d in stage_job_var)
            dep_vars_str = dep_vars if dep_vars else "$" + stage_job_var.get(deps[0], "NONE")
            lines.append(f"# Submit: {s.id} (after {', '.join(deps)})")
            lines.append(f'{var_name}=$(cd "$ROOT/{s.directory}" && '
                        f'sbatch --dependency=afterok{"" if not dep_vars else ":"}{dep_vars_str} run.sbatch | '
                        f"awk '{{print $NF}}')")

        lines.append(f'echo "{s.id}: ${var_name}"')
        stage_job_var[s.id] = var_name
        lines.append("")

    lines.append('echo "=== All jobs submitted ==="')
    lines.append("squeue -u $USER")
    return "\n".join(lines) + "\n"


def build_stage_readme(stage: StageSpec, plan: WorkflowPlan) -> str:
    """Build a README.md for a single stage."""
    deps = ", ".join(stage.depends_on) if stage.depends_on else "none"
    return f"""# Stage: {stage.id}

- **Kind:** {stage.kind.value}
- **Program:** {stage.executable or 'manual'}
- **Input:** {stage.input_file or 'N/A'}
- **Output:** {stage.output_file or 'N/A'}
- **Cores:** {stage.cores}
- **Walltime:** {stage.walltime}
- **Depends on:** {deps}

## Submit

```bash
sbatch run.sbatch
```

## Verify

```bash
grep "JOB DONE" {stage.output_file or '*.out'}
```
"""


def _safe_job_name(stage: StageSpec) -> str:
    """Slurm-safe job name (max ~15 chars, no special chars)."""
    name = stage.id.replace("-", "_")
    return name[:15]
