"""Research-domain models for VibeDFT claim/evidence review."""

from .models import (
    AnalysisResult,
    ArtifactLineage,
    ArtifactType,
    ClaimStatus,
    ClaimType,
    ComparisonSet,
    EvidenceMaturity,
    EvidenceRef,
    EvidenceRequirement,
    FixtureManifest,
    GateDecision,
    GateVerdict,
    LiteratureProtocol,
    LLMTaskCard,
    PhysicsDescriptor,
    PhysicsVerdict,
    ReliabilityLevel,
    ResearchQuestion,
    ResultStatus,
    Route,
    ScientificClaim,
    WorkflowStageResult,
)
from .lineage import (
    CompatibilityResult,
    detect_case_lineage_warnings,
    parameter_fingerprints_compatible,
)
from .scanner import scan_case
from .gates import evaluate_claim
from .manifest import fixture_manifest_from_dict, load_fixture_manifest
from .regression import (
    REALDATA_REGRESSION_REQUIREMENTS,
    RealDataFixtureRequirement,
    run_realdata_parser_smoke,
    validate_realdata_regression_manifest,
)
from .case_pipeline import (
    CASE_PIPELINE_STAGE_IDS,
    BatchEvidencePipelineResult,
    CaseEvidencePipelineResult,
    batch_evidence_pipeline_payload,
    case_evidence_pipeline_payload,
    discover_case_directories,
    run_batch_evidence_pipeline,
    run_case_evidence_pipeline,
)
from .report import (
    build_evidence_pack_from_stages,
    render_claim_report,
    render_evidence_backed_summary,
    workflow_stage_from_analysis,
)

__all__ = [
    "AnalysisResult",
    "ArtifactLineage",
    "ArtifactType",
    "build_evidence_pack_from_stages",
    "CASE_PIPELINE_STAGE_IDS",
    "BatchEvidencePipelineResult",
    "CaseEvidencePipelineResult",
    "batch_evidence_pipeline_payload",
    "case_evidence_pipeline_payload",
    "ClaimStatus",
    "ClaimType",
    "CompatibilityResult",
    "ComparisonSet",
    "detect_case_lineage_warnings",
    "EvidenceMaturity",
    "EvidenceRef",
    "EvidenceRequirement",
    "evaluate_claim",
    "FixtureManifest",
    "GateDecision",
    "GateVerdict",
    "fixture_manifest_from_dict",
    "LiteratureProtocol",
    "LLMTaskCard",
    "load_fixture_manifest",
    "PhysicsDescriptor",
    "PhysicsVerdict",
    "REALDATA_REGRESSION_REQUIREMENTS",
    "RealDataFixtureRequirement",
    "ResearchQuestion",
    "ReliabilityLevel",
    "render_claim_report",
    "render_evidence_backed_summary",
    "run_batch_evidence_pipeline",
    "run_realdata_parser_smoke",
    "run_case_evidence_pipeline",
    "parameter_fingerprints_compatible",
    "ResultStatus",
    "Route",
    "scan_case",
    "ScientificClaim",
    "discover_case_directories",
    "validate_realdata_regression_manifest",
    "workflow_stage_from_analysis",
    "WorkflowStageResult",
]
